steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'asia.gcr.io/dazzling-pillar-328210/bitbucket.org/isbtotogroup/isbpanel_backend:latest',
        '.',
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        'asia.gcr.io/dazzling-pillar-328210/bitbucket.org/isbtotogroup/isbpanel_backend',
      ]
